apiVersion: v1
kind: ResourceQuota
metadata:
  name: platform-apps-quota
  namespace: platform-apps
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 10Gi
    limits.cpu: "20"
    limits.memory: 20Gi
    persistentvolumeclaims: "10"
    pods: "50"
