apiVersion: v1
kind: ResourceQuota
metadata:
  name: platform-data-quota
  namespace: platform-data
spec:
  hard:
    requests.cpu: "5"
    requests.memory: 5Gi
    limits.cpu: "10"
    limits.memory: 10Gi
    persistentvolumeclaims: "20"
    pods: "20"
