# Install: kubectl apply -f operators/zalando-postgres/install.yaml
# Official: https://github.com/zalando/postgres-operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-operator
  namespace: operators
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgres-operator
rules:
  - apiGroups: ["acid.zalan.do"]
    resources: ["postgresqls", "postgresqls/status", "operatorconfigurations"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["configmaps", "events", "endpoints", "secrets", "services", "pods", "persistentvolumeclaims"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "deployments"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["*"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: postgres-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: postgres-operator
subjects:
  - kind: ServiceAccount
    name: postgres-operator
    namespace: operators
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-operator
  namespace: operators
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-operator
  template:
    metadata:
      labels:
        name: postgres-operator
    spec:
      serviceAccountName: postgres-operator
      containers:
        - name: postgres-operator
          image: ghcr.io/zalando/postgres-operator:v1.12.2
          env:
            - name: WATCHED_NAMESPACE
              value: "*"
          resources:
            requests:
              cpu: 100m
              memory: 250Mi
            limits:
              cpu: 500m
              memory: 500Mi
